### ISSUE TITLE
Convert this tutorial to Windows...

### ISSUE THREAD

**Issue by SkybuckFlying** [radixdlt/babylon-node#931]
https://docs.radixdlt.com/v1/docs/node-setup-systemd

This tutorial is closest to how Windows Radix Node would be set up, but some of it is a little peculiar and could lead to problems.

Would be nice to have something like this for Windows and tested successfull...

**Comment by dhedey** [comment]
The node does work bare metal on Windows, and a number of validators do run on Windows.

But yes, the documentation is sparse at present.
