### ISSUE TITLE
Storing KeyStore password in windows environment variable does not feel safe and can be retrieved.

### ISSUE THREAD

**Issue by SkybuckFlying** [radixdlt/babylon-node#935]
All set windows environment variables can be retrieved with the power shell command:

gci env:* | sort-object name

There might also be other techniques how applications could retrieve these settings,

I believe Delphi development environment also retrieves windows environment variables.

Therefore I recommend to pass the keystore password as a command line parameter or preferably via a default.config setting.

NOT via windows environment variable: 

RADIX_NODE_KEYSTORE_PASSWORD

This is the first time EVER that I have seen a software application do this... very weird/strange ! ;)

**Comment by dhedey** [comment]
The keystore itself is already a file, so the password is an optional second factor to unlock. We will bear your input in mind regarding Windows when this is revisited.
