### ISSUE TITLE
Cannot register validator easy via Android Tablet.

### ISSUE THREAD

**Issue by SkybuckFlying** [radixdlt/babylon-node#973]
1. Have to Scan QR Code ?! Why such nonsense and complexities ?!

2. It also requires a special webbrowser: chrome/edge for the connector.

Apperently now also mobile phone required and also very difficult setup with all kinds of codes.

Way too difficult. But I will keep trying.

I just spent a few hours to configure the wi-fi modem to make these crap tablets/phones work... bleh...

Now I need to find a QR code scanner for Windows 11.

Retards are impressed by complexity, do you think you qualify ? ;)

**Comment by SkybuckFlying** [comment]
WTF do I do with the code after scanning it with QR Scanner ?!

This is so retardedly complex, it's a fucking benny hill jooookkkeee !

**Comment by SkybuckFlying** [comment]
VIDEO IS OLD YOU DUMBASSES...

IT LOOKS DIFFERENT NOW ! LOL.

I AM SURPRISED THERE ARE 100+ VALIDATORS, AMAZING...

MAYBE THEY REGISTERED IN THE PAST.

**Comment by SkybuckFlying** [comment]
OH WAIT, ONE MUST GO BACK FROM THE ACCOUNT, INTO THE MAIN WINDOW... NICE AND CONFUSING...

WHY WOULD I WANT TO LINK FROM MAIN WINDOW, IT MAKES NO SENSE...

THERE ARE MULTIPLE ACCOUNTS... DUH... SO BAD... YOU HAVE LOTS OF ISSUES.

**Comment by SkybuckFlying** [comment]
THE ANDROID CAMERA IS NOT WORKING... THE AMMOUNT OF TECHNOLOGY TO GET THIS WORKING IS INSANE

YOU ARE FUCKING RETARDS I HOPE YOUR COIN BURNS IN HELL, IT WILL.

STUPID SHIT...

I KEEP TRYING THOUGH...

**Comment by SkybuckFlying** [comment]
FINALLY CONNECTED ?!

WILL THIS EVEN WORK AFTER I DELETE ALL AND TRY TO RE-DO IT ?! I HOPE SO...

**Comment by SkybuckFlying** [comment]
MORE STUPID COMPLEXITY:

NOW I HAVE TO LOGIN AND CREATE PERSONA...

HOW MUCH FUCKING SHIT DO I HAVE TO BARE FOR THIS SHIT OH MY GOD.

**Comment by SkybuckFlying** [comment]
37% PROCENT POWER LEFT ON THIS THING... I HOPE IT DONT RUN OUT...

I FORGOT TO BRING A CHARGING CABLE OR WHATEVER... I HOPE YOUR FUCKING MOBILE PHONE RUNS OUT OF POWER FOREVER LOL. HAHAHAHAHAHAHA

**Comment by SkybuckFlying** [comment]
I NEED VISUAL STUDIO CODE, TO FORMAT YOUR JSON CRAP FROM THE NODE, IT'S KINDA ANNOYING YOU KNOW...

**Comment by SkybuckFlying** [comment]
NOW I NEED TO FIND NOTEPAD++ OFFICIAL SITE, SO I DON'T GET HACKED, TRYING TO PARSE YOUR NODE CRAP:

{"public_key_hex": ETC

**Comment by SkybuckFlying** [comment]
I AM NOT THERE YET LOL, I NEED TO DOWNLOAD NOTEPAD++ PLUGIN PROBABLY TO FORMAT JSON NICELY...

**Comment by SkybuckFlying** [comment]
Now I ask AI in bing for this plugin cause VS code way too complex interface haha,

**Comment by SkybuckFlying** [comment]
You know what forget... let's do notepad++ first..

**Comment by SkybuckFlying** [comment]
Need this site too, which tells you how to install it, the sourceforge page didn't haha:

https://stackoverflow.com/questions/1560464/how-to-reformat-json-in-notepad

Nerd that made this assumes we already know... so maybe idiots online... hate it.

**Comment by SkybuckFlying** [comment]
It's quite simple though, place dll in some folder, but you must just happen to knows this, how is anybody happen to know this... could be script could be anything... proceeding.

**Comment by SkybuckFlying** [comment]
NOPE IT WAS NOT AS EASY...

THERE ARE MULTIPLE FOLDERS TO CHOOSE FROM IN THE PLUGIN FOLDER... LOL... SO MUCH STUPID COMPLEXITY...

FUNNY...

 I ALREADY SET THIS SHIT UP ON MY PREVIOUS COMPUTER... BUT BECAUSE OF NEW WINDOWS MUST RESETUP EVERYTHING THX MICROSHIT.

**Comment by SkybuckFlying** [comment]
There was an easier way... build in plugin systemmm json tools... done... pretty print... deleting dll just in case from sourceforge..

**Comment by SkybuckFlying** [comment]
EVEN YOUR TICKER IS RETARDED: XRD

I CAN NEVER REMEMBER IT... WHY NOT RDX ?!

YOU FUCKERS ARE SO STUPID... THIS COIN IS DOOMED FROM THE START.

SCAMMER WILL MAKE FAKE COIN CALLED RDX AND YOU ALL DOOMED, FU YOU ALL TO HELL. HAHAHA,.

**Comment by SkybuckFlying** [comment]
huh ?

Registering as a validator
First of all we make sure that our node is running in validator mode to register the correct node key.

switch-mode validator

how to do this from cmd.exe ?

**Comment by SkybuckFlying** [comment]
I removed the comments, still not working <snip> for privacy:

CALL_METHOD
    Address("<snip>")
    "withdraw"
    Address("resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd")
    Decimal("2000");
TAKE_FROM_WORKTOP
    Address("resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd")
    Decimal("2000")
    Bucket("validator_creation_fee");
CREATE_VALIDATOR
    Bytes("<snip>")
    # The following argument is the "Fee factor" - a decimal between 0 and 1
    #  which describes the proportion of the emissions that the owner will take.
    #  Unlike Olympia, this is expressed as a decimal proportion, not as basis points.
    Decimal("0.0098")
    Bucket("validator_creation_fee");
CALL_METHOD
    Address("<snip>")
    "try_deposit_batch_or_abort"
    Expression("ENTIRE_WORKTOP")
    None;

What is wrong ?

**Comment by dhedey** [comment]
Answered in https://github.com/radixdlt/babylon-node/issues/975
