### ISSUE TITLE
Add additional password to accounts on mobile wallet.

### ISSUE THREAD

**Issue by SkybuckFlying** [radixdlt/babylon-node#974]
I create these wallets on the mobile device of my mother...

Now my mother can access these accounts... or anybody else that uses her devices.

Pretty f-ing stupid !

Also removing the app and accounts is hard, which now I will have to do, but would like to do anyway.

REQUEST:

ADD BASIC PASSWORD TO ACCOUNT ON MOBILE WALLET.

THIS IS HILARIOUS, YOU TRY TO SECURE EVERYTHING EXCEPT THE MOST IMPORTANT PART, THE WALLET ITSELF ! LOL.

**Comment by dhedey** [comment]
The wallet is protected by phone unlock, requiring password/biometrics. Soon MFA will be supported in the wallet.

If you wish to provide further feedback about your use case, please email hello@radixdlt.com or provide wallet feedback on Discord: https://discord.com/channels/417762285172555786/762831287266181140
